#!/usr/bin/env bash

set -euo pipefail

die() {
    echo "Error:" "$@"
    exit 1
}

build_dir=.build/
protocol_dir="$build_dir/protocols"

make_protocol_headers() {
    # wayland-scanner is a tool which generates C headers and rigging
    # for Wayland protocols, which are specified in XML. wlroots requires
    # you to rig these up to your build system yourself and provide them
    # in the include path.
    scanner=$(pkg-config --variable=wayland_scanner wayland-scanner) || \
        die "wayland-scanner not found"
    wl_protocols_xml=$(pkg-config --variable=pkgdatadir wayland-protocols) || \
        die "wayland-protocols not found"
    wlr_protocols_xml=$(pkg-config --variable=pkgdatadir wlr-protocols) || \
        die "wlr-protocols not found"

    mkdir -p "$protocol_dir"
    xdg_shell_h="$protocol_dir/xdg-shell-protocol.h"
    [[ -f "$xdg_shell_h" ]] ||
    "$scanner" server-header \
        "$wl_protocols_xml"/stable/xdg-shell/xdg-shell.xml "$xdg_shell_h"

    layer_shell_h="$protocol_dir/wlr-layer-shell-unstable-v1-protocol.h"
    [[ -f "$layer_shell_h" ]] ||
    "$scanner" server-header \
        "$wlr_protocols_xml"/unstable/wlr-layer-shell-unstable-v1.xml "$layer_shell_h"
}

make_protocol_headers
exec cabal "$@"
